
export default {
  DASHBOARD:"/dashboard",
  BOARD_NOW: "/board/now",
  STYLE_GUIDE:"/styleguide",
  CLIENT_MANAGEMENT: "/clientmanagement",
  CLIENT_CREATE:"/client/create",
  CLIENT_DETAIL: "/client/detail/",
  CLIENT_UPDATE:"/client/update/",
  STATE_CITY: "/state",
  CITY: "/city/",
  PROGRAM: "/program",
  PROGRAM_CREATE: "/program/create",
  PROGRAM_UPDATE: "/program/update/",
  PROGRAM_DETAIL: "/program/detail/",
  POPULAR_CITIES: "/popularcities",
  PET_MASTER: "/pet",
  PET_CREATE: "/pet/create",
  PET_UPDATE: "/pet/update/",
  APP_USERS: "/appusers",
  APP_DETAIL: "/appusers/detail/",
  QUIZ:"/quiz",
  QUIZ_CREATE:"/quiz/create",
  QUIZ_UPDATE:"/quiz/update/",
  QUIZ_DETAIL:"/quiz/detail/",
  QUIZ_DUPLICATE:"/quiz/duplicate/",
  HEALTH_TIPS: "/healthtips",
  HEALTH_CREATE: "/healthtips/create",
  HEALTH_UPDATE: "/healthtips/update/",
  HEALTH_DETAIL: "/healthtips/detail/",
  HEALTH_DUPLICATE: "/healthtips/duplicate/",
  APP_SETTINGS: "/appsettings",
  DOCTOR_MASTER: "/doctor",
  REWARD:"/reward",
  REWARD_CREATE:"/reward/create",
  REWARD_UPDATE:"/reward/update/",
  REWARD_DETAIL:"/reward/detail/",
  GIFT: "/giftStore",
  GIFT_CREATE: "/giftStore/create",
  GIFT_UPDATE: "/giftStore/update/",
  GIFT_DETAIL: "/giftStore/detail/",
  REPORTED: "/reportedSideEffects",
  REPORTED_DETAIL: "/reportedSideEffects/detail",
  AUDIT_CREATE: "/auditTrialLog/create",
  ADMIN:"/adminUsers",
  ADMIN_CREATE:"/adminUsers/create",
  ADMIN_UPDATE:"/adminUsers/update/",
  ADMIN_DETAIL:"/adminUsers/detail/",
  ADMIN_PRIVILEGES: "/admin/users/detail/privileges",
  ROLES:'/roles',
  ROLE_CREATE: '/role/create',
  ROLE_UPDATE: '/role/update/',
  ROLE_DETAIL: '/role/detail/',
  VITAL_MASTER: "/vital",
  VITAL_CREATE: "/vital/create",
  VITAL_UPDATE: "/vital/update/",
  VITAL_DETAIL: "/vital/detail/",
  LANGUAGE_MASTER: "/language",
  LANGUAGE_CREATE: "/language/create",
  LANGUAGE_UPDATE: "/language/update/",
  LEARNING_HUB_MASTER: "/learning",
  LEARNING_HUB_CREATE: "/learning/create",
  LEARNING_HUB_UPDATE: "/learning/update/",
  LEARNING_HUB_DETAIL: "/learning/detail/",
  VIDEOS_MASTER: "/videos",
  VIDEOS_CREATE: "/videos/create",
  VIDEOS_UPDATE: "/videos/update/",
  VIDEOS_DETAIL: "/videos/detail/",

  PROGRAM_DASHBOARD:"/program/dashboard",
  USER_QUERIES: "/user/queries",
  USER_QUERIES_DETAIL: "/user/queries/detail/",
  WELCOME: "/welcome",
  USER_ENGAGEMENT_DASHBOARD: "/user/engagement/dashboard",
  PROGRAM_QUERIES: "/user/program/queries",
  PROGRAM_QUERIES_DETAIL: "/user/program/queries/detail/",
  CHAT_MASTER: "/chat/master",

  DOCTOR_DASHBOARD:"/doctor/dashboard",

  ENGINEERING_DASHBOARD: "/engineer",
  MANGER_DASHBOARD: "/manager",
};
